name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: shubhu-io
          outputs: |
            dist/github-snake.svg?palette=github-light
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=%2300d4ff&color_dots=%23ebedf0,%239bdcff,%236ab7ff,%233b82f6,%231d4ed8&color_background=%230d1117

      - name: Deploy to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git rm -rf .
          cp dist/* .
          git add .
          git commit -m "Update snake images"
          git push -f origin output
